"""
MUBI Supported Countries

Single source of truth for all countries supported by MUBI.
Data sourced from mubifinder.com

VPN Tier Classification (based on 2024/2025 Global Internet Speed Indices):
    1 = Hyper-Speed Elite (300+ Mbps infrastructure) - Best for streaming
    2 = High Performance (200-300 Mbps) - Reliable, rarely buffers
    3 = Good/Average (100-199 Mbps) - Good for HD streaming
    4 = Developing Infrastructure (<90 Mbps) - May have latency issues
"""

# Dictionary with ISO 3166-1 alpha-2 code as key
COUNTRIES = {
    "af": {"name": "Afghanistan", "vpn_tier": 4},
    "al": {"name": "Albania", "vpn_tier": 4},
    "dz": {"name": "Algeria", "vpn_tier": 4},
    "as": {"name": "American Samoa", "vpn_tier": 4},
    "ad": {"name": "Andorra", "vpn_tier": 4},
    "ao": {"name": "Angola", "vpn_tier": 4},
    "ai": {"name": "Anguilla", "vpn_tier": 4},
    "aq": {"name": "Antarctica", "vpn_tier": 4},
    "ag": {"name": "Antigua and Barbuda", "vpn_tier": 4},
    "ar": {"name": "Argentina", "vpn_tier": 4},
    "am": {"name": "Armenia", "vpn_tier": 4},
    "aw": {"name": "Aruba", "vpn_tier": 4},
    "au": {"name": "Australia", "vpn_tier": 4},
    "at": {"name": "Austria", "vpn_tier": 4},
    "az": {"name": "Azerbaijan", "vpn_tier": 4},
    "bs": {"name": "Bahamas", "vpn_tier": 4},
    "bh": {"name": "Bahrain", "vpn_tier": 4},
    "bd": {"name": "Bangladesh", "vpn_tier": 4},
    "bb": {"name": "Barbados", "vpn_tier": 4},
    "by": {"name": "Belarus", "vpn_tier": 4},
    "be": {"name": "Belgium", "vpn_tier": 4},
    "bz": {"name": "Belize", "vpn_tier": 4},
    "bj": {"name": "Benin", "vpn_tier": 4},
    "bm": {"name": "Bermuda", "vpn_tier": 4},
    "bt": {"name": "Bhutan", "vpn_tier": 4},
    "bo": {"name": "Bolivia", "vpn_tier": 4},
    "bq": {"name": "Bonaire, Sint Eustatius and Saba", "vpn_tier": 4},
    "ba": {"name": "Bosnia and Herzegovina", "vpn_tier": 4},
    "bw": {"name": "Botswana", "vpn_tier": 4},
    "br": {"name": "Brazil", "vpn_tier": 3},
    "io": {"name": "British Indian Ocean Territory", "vpn_tier": 4},
    "bn": {"name": "Brunei Darussalam", "vpn_tier": 4},
    "bg": {"name": "Bulgaria", "vpn_tier": 4},
    "bf": {"name": "Burkina Faso", "vpn_tier": 4},
    "bi": {"name": "Burundi", "vpn_tier": 4},
    "kh": {"name": "Cambodia", "vpn_tier": 4},
    "cm": {"name": "Cameroon", "vpn_tier": 4},
    "ca": {"name": "Canada", "vpn_tier": 2},
    "cv": {"name": "Cape Verde", "vpn_tier": 4},
    "ky": {"name": "Cayman Islands", "vpn_tier": 4},
    "cf": {"name": "Central African Republic", "vpn_tier": 4},
    "td": {"name": "Chad", "vpn_tier": 4},
    "cl": {"name": "Chile", "vpn_tier": 1},
    "cn": {"name": "China", "vpn_tier": 4},
    "cx": {"name": "Christmas Island", "vpn_tier": 4},
    "cc": {"name": "Cocos (Keeling) Islands", "vpn_tier": 4},
    "co": {"name": "Colombia", "vpn_tier": 4},
    "km": {"name": "Comoros", "vpn_tier": 4},
    "cg": {"name": "Congo", "vpn_tier": 4},
    "cd": {"name": "Congo, Democratic Republic", "vpn_tier": 4},
    "ck": {"name": "Cook Islands", "vpn_tier": 4},
    "cr": {"name": "Costa Rica", "vpn_tier": 4},
    "hr": {"name": "Croatia", "vpn_tier": 4},
    "cu": {"name": "Cuba", "vpn_tier": 4},
    "cw": {"name": "Curaçao", "vpn_tier": 4},
    "cy": {"name": "Cyprus", "vpn_tier": 4},
    "cz": {"name": "Czech Republic", "vpn_tier": 4},
    "dk": {"name": "Denmark", "vpn_tier": 2},
    "dj": {"name": "Djibouti", "vpn_tier": 4},
    "dm": {"name": "Dominica", "vpn_tier": 4},
    "do": {"name": "Dominican Republic", "vpn_tier": 4},
    "ec": {"name": "Ecuador", "vpn_tier": 4},
    "eg": {"name": "Egypt", "vpn_tier": 4},
    "sv": {"name": "El Salvador", "vpn_tier": 4},
    "gq": {"name": "Equatorial Guinea", "vpn_tier": 4},
    "er": {"name": "Eritrea", "vpn_tier": 4},
    "ee": {"name": "Estonia", "vpn_tier": 4},
    "sz": {"name": "Eswatini", "vpn_tier": 4},
    "et": {"name": "Ethiopia", "vpn_tier": 4},
    "fk": {"name": "Falkland Islands (Malvinas)", "vpn_tier": 4},
    "fo": {"name": "Faroe Islands", "vpn_tier": 4},
    "fj": {"name": "Fiji", "vpn_tier": 4},
    "fi": {"name": "Finland", "vpn_tier": 3},
    "fr": {"name": "France", "vpn_tier": 1},
    "gf": {"name": "French Guiana", "vpn_tier": 4},
    "pf": {"name": "French Polynesia", "vpn_tier": 4},
    "tf": {"name": "French Southern Territories", "vpn_tier": 4},
    "ga": {"name": "Gabon", "vpn_tier": 4},
    "gm": {"name": "Gambia", "vpn_tier": 4},
    "ge": {"name": "Georgia", "vpn_tier": 4},
    "de": {"name": "Germany", "vpn_tier": 3},
    "gh": {"name": "Ghana", "vpn_tier": 4},
    "gi": {"name": "Gibraltar", "vpn_tier": 4},
    "gr": {"name": "Greece", "vpn_tier": 4},
    "gl": {"name": "Greenland", "vpn_tier": 4},
    "gd": {"name": "Grenada", "vpn_tier": 4},
    "gp": {"name": "Guadeloupe", "vpn_tier": 4},
    "gu": {"name": "Guam", "vpn_tier": 4},
    "gt": {"name": "Guatemala", "vpn_tier": 4},
    "gg": {"name": "Guernsey", "vpn_tier": 4},
    "gn": {"name": "Guinea", "vpn_tier": 4},
    "gw": {"name": "Guinea-Bissau", "vpn_tier": 4},
    "gy": {"name": "Guyana", "vpn_tier": 4},
    "ht": {"name": "Haiti", "vpn_tier": 4},
    "hm": {"name": "Heard Island and McDonald Islands", "vpn_tier": 4},
    "hn": {"name": "Honduras", "vpn_tier": 4},
    "hk": {"name": "Hong Kong", "vpn_tier": 1},
    "hu": {"name": "Hungary", "vpn_tier": 2},
    "is": {"name": "Iceland", "vpn_tier": 1},
    "in": {"name": "India", "vpn_tier": 4},
    "id": {"name": "Indonesia", "vpn_tier": 4},
    "ir": {"name": "Iran", "vpn_tier": 4},
    "iq": {"name": "Iraq", "vpn_tier": 4},
    "ie": {"name": "Ireland", "vpn_tier": 3},
    "im": {"name": "Isle of Man", "vpn_tier": 4},
    "il": {"name": "Israel", "vpn_tier": 2},
    "it": {"name": "Italy", "vpn_tier": 4},
    "ci": {"name": "Ivory Coast", "vpn_tier": 4},
    "jm": {"name": "Jamaica", "vpn_tier": 4},
    "jp": {"name": "Japan", "vpn_tier": 2},
    "je": {"name": "Jersey", "vpn_tier": 4},
    "jo": {"name": "Jordan", "vpn_tier": 4},
    "kz": {"name": "Kazakhstan", "vpn_tier": 4},
    "ke": {"name": "Kenya", "vpn_tier": 4},
    "ki": {"name": "Kiribati", "vpn_tier": 4},
    "kw": {"name": "Kuwait", "vpn_tier": 4},
    "kg": {"name": "Kyrgyzstan", "vpn_tier": 4},
    "la": {"name": "Laos", "vpn_tier": 4},
    "lv": {"name": "Latvia", "vpn_tier": 4},
    "lb": {"name": "Lebanon", "vpn_tier": 4},
    "ls": {"name": "Lesotho", "vpn_tier": 4},
    "lr": {"name": "Liberia", "vpn_tier": 4},
    "ly": {"name": "Libya", "vpn_tier": 4},
    "li": {"name": "Liechtenstein", "vpn_tier": 4},
    "lt": {"name": "Lithuania", "vpn_tier": 4},
    "lu": {"name": "Luxembourg", "vpn_tier": 4},
    "mo": {"name": "Macao", "vpn_tier": 4},
    "mk": {"name": "Macedonia", "vpn_tier": 4},
    "mg": {"name": "Madagascar", "vpn_tier": 4},
    "mw": {"name": "Malawi", "vpn_tier": 4},
    "my": {"name": "Malaysia", "vpn_tier": 4},
    "mv": {"name": "Maldives", "vpn_tier": 4},
    "ml": {"name": "Mali", "vpn_tier": 4},
    "mt": {"name": "Malta", "vpn_tier": 4},
    "mh": {"name": "Marshall Islands", "vpn_tier": 4},
    "mq": {"name": "Martinique", "vpn_tier": 4},
    "mr": {"name": "Mauritania", "vpn_tier": 4},
    "mu": {"name": "Mauritius", "vpn_tier": 4},
    "yt": {"name": "Mayotte", "vpn_tier": 4},
    "mx": {"name": "Mexico", "vpn_tier": 4},
    "fm": {"name": "Micronesia", "vpn_tier": 4},
    "md": {"name": "Moldova", "vpn_tier": 4},
    "mc": {"name": "Monaco", "vpn_tier": 4},
    "mn": {"name": "Mongolia", "vpn_tier": 4},
    "me": {"name": "Montenegro", "vpn_tier": 4},
    "ms": {"name": "Montserrat", "vpn_tier": 4},
    "ma": {"name": "Morocco", "vpn_tier": 4},
    "mz": {"name": "Mozambique", "vpn_tier": 4},
    "mm": {"name": "Myanmar", "vpn_tier": 4},
    "na": {"name": "Namibia", "vpn_tier": 4},
    "nr": {"name": "Nauru", "vpn_tier": 4},
    "np": {"name": "Nepal", "vpn_tier": 4},
    "nl": {"name": "Netherlands", "vpn_tier": 2},
    "nc": {"name": "New Caledonia", "vpn_tier": 4},
    "nz": {"name": "New Zealand", "vpn_tier": 3},
    "ni": {"name": "Nicaragua", "vpn_tier": 4},
    "ne": {"name": "Niger", "vpn_tier": 4},
    "ng": {"name": "Nigeria", "vpn_tier": 4},
    "nu": {"name": "Niue", "vpn_tier": 4},
    "nf": {"name": "Norfolk Island", "vpn_tier": 4},
    "kp": {"name": "North Korea", "vpn_tier": 4},
    "mp": {"name": "Northern Mariana Islands", "vpn_tier": 4},
    "no": {"name": "Norway", "vpn_tier": 3},
    "om": {"name": "Oman", "vpn_tier": 4},
    "pk": {"name": "Pakistan", "vpn_tier": 4},
    "pw": {"name": "Palau", "vpn_tier": 4},
    "ps": {"name": "Palestine", "vpn_tier": 4},
    "pa": {"name": "Panama", "vpn_tier": 4},
    "pg": {"name": "Papua New Guinea", "vpn_tier": 4},
    "py": {"name": "Paraguay", "vpn_tier": 4},
    "pe": {"name": "Peru", "vpn_tier": 4},
    "ph": {"name": "Philippines", "vpn_tier": 4},
    "pn": {"name": "Pitcairn", "vpn_tier": 4},
    "pl": {"name": "Poland", "vpn_tier": 3},
    "pt": {"name": "Portugal", "vpn_tier": 3},
    "pr": {"name": "Puerto Rico", "vpn_tier": 4},
    "qa": {"name": "Qatar", "vpn_tier": 4},
    "ro": {"name": "Romania", "vpn_tier": 2},
    "ru": {"name": "Russian Federation", "vpn_tier": 4},
    "rw": {"name": "Rwanda", "vpn_tier": 4},
    "re": {"name": "Réunion", "vpn_tier": 4},
    "bl": {"name": "Saint Barthélemy", "vpn_tier": 4},
    "sh": {"name": "Saint Helena", "vpn_tier": 4},
    "kn": {"name": "Saint Kitts and Nevis", "vpn_tier": 4},
    "lc": {"name": "Saint Lucia", "vpn_tier": 4},
    "mf": {"name": "Saint Martin (French part)", "vpn_tier": 4},
    "pm": {"name": "Saint Pierre and Miquelon", "vpn_tier": 4},
    "vc": {"name": "Saint Vincent and the Grenadines", "vpn_tier": 4},
    "ws": {"name": "Samoa", "vpn_tier": 4},
    "sm": {"name": "San Marino", "vpn_tier": 4},
    "st": {"name": "Sao Tome and Principe", "vpn_tier": 4},
    "sa": {"name": "Saudi Arabia", "vpn_tier": 4},
    "sn": {"name": "Senegal", "vpn_tier": 4},
    "rs": {"name": "Serbia", "vpn_tier": 4},
    "sc": {"name": "Seychelles", "vpn_tier": 4},
    "sl": {"name": "Sierra Leone", "vpn_tier": 4},
    "sg": {"name": "Singapore", "vpn_tier": 1},
    "sx": {"name": "Sint Maarten (Dutch part)", "vpn_tier": 4},
    "sk": {"name": "Slovakia", "vpn_tier": 4},
    "si": {"name": "Slovenia", "vpn_tier": 4},
    "sb": {"name": "Solomon Islands", "vpn_tier": 4},
    "so": {"name": "Somalia", "vpn_tier": 4},
    "za": {"name": "South Africa", "vpn_tier": 4},
    "gs": {"name": "South Georgia and the South Sandwich Islands", "vpn_tier": 4},
    "kr": {"name": "South Korea", "vpn_tier": 2},
    "ss": {"name": "South Sudan", "vpn_tier": 4},
    "es": {"name": "Spain", "vpn_tier": 2},
    "lk": {"name": "Sri Lanka", "vpn_tier": 4},
    "sd": {"name": "Sudan", "vpn_tier": 4},
    "sr": {"name": "Suriname", "vpn_tier": 4},
    "sj": {"name": "Svalbard and Jan Mayen", "vpn_tier": 4},
    "se": {"name": "Sweden", "vpn_tier": 3},
    "ch": {"name": "Switzerland", "vpn_tier": 2},
    "sy": {"name": "Syria", "vpn_tier": 4},
    "tw": {"name": "Taiwan", "vpn_tier": 4},
    "tj": {"name": "Tajikistan", "vpn_tier": 4},
    "tz": {"name": "Tanzania", "vpn_tier": 4},
    "th": {"name": "Thailand", "vpn_tier": 1},
    "tl": {"name": "Timor-Leste", "vpn_tier": 4},
    "tg": {"name": "Togo", "vpn_tier": 4},
    "tk": {"name": "Tokelau", "vpn_tier": 4},
    "to": {"name": "Tonga", "vpn_tier": 4},
    "tt": {"name": "Trinidad and Tobago", "vpn_tier": 4},
    "tn": {"name": "Tunisia", "vpn_tier": 4},
    "tr": {"name": "Turkey", "vpn_tier": 4},
    "tm": {"name": "Turkmenistan", "vpn_tier": 4},
    "tc": {"name": "Turks and Caicos Islands", "vpn_tier": 4},
    "tv": {"name": "Tuvalu", "vpn_tier": 4},
    "ug": {"name": "Uganda", "vpn_tier": 4},
    "ua": {"name": "Ukraine", "vpn_tier": 4},
    "ae": {"name": "United Arab Emirates", "vpn_tier": 1},
    "gb": {"name": "United Kingdom", "vpn_tier": 3},
    "us": {"name": "United States", "vpn_tier": 1},
    "um": {"name": "United States Minor Outlying Islands", "vpn_tier": 4},
    "uy": {"name": "Uruguay", "vpn_tier": 4},
    "uz": {"name": "Uzbekistan", "vpn_tier": 4},
    "vu": {"name": "Vanuatu", "vpn_tier": 4},
    "va": {"name": "Vatican City", "vpn_tier": 4},
    "ve": {"name": "Venezuela", "vpn_tier": 4},
    "vn": {"name": "Viet Nam", "vpn_tier": 4},
    "vg": {"name": "Virgin Islands, British", "vpn_tier": 4},
    "vi": {"name": "Virgin Islands, U.S.", "vpn_tier": 4},
    "wf": {"name": "Wallis and Futuna", "vpn_tier": 4},
    "eh": {"name": "Western Sahara", "vpn_tier": 4},
    "ye": {"name": "Yemen", "vpn_tier": 4},
    "zm": {"name": "Zambia", "vpn_tier": 4},
    "zw": {"name": "Zimbabwe", "vpn_tier": 4},
    "ax": {"name": "Åland Islands", "vpn_tier": 4},
}


def get_tier1_countries():
    """Get Hyper-Speed Elite countries (300+ Mbps infrastructure)."""
    return {code: data for code, data in COUNTRIES.items() if data["vpn_tier"] == 1}


def get_tier2_countries():
    """Get High Performance countries (200-300 Mbps)."""
    return {code: data for code, data in COUNTRIES.items() if data["vpn_tier"] == 2}


def get_tier3_countries():
    """Get Good/Average countries (100-199 Mbps)."""
    return {code: data for code, data in COUNTRIES.items() if data["vpn_tier"] == 3}


def get_tier4_countries():
    """Get Developing Infrastructure countries (<90 Mbps)."""
    return {code: data for code, data in COUNTRIES.items() if data["vpn_tier"] == 4}


def get_top_countries():
    """Get top countries (tier 1, 2, and 3) recommended for streaming."""
    return {code: data for code, data in COUNTRIES.items() if data["vpn_tier"] <= 3}


def get_streaming_countries():
    """Get countries with best streaming performance (tier 1 and 2 only)."""
    return {code: data for code, data in COUNTRIES.items() if data["vpn_tier"] <= 2}


def get_country_name(code):
    """Get country name by ISO code."""
    country = COUNTRIES.get(code.lower())
    return country["name"] if country else None


def get_all_codes():
    """Get list of all country ISO codes."""
    return list(COUNTRIES.keys())
